# Generated by Django 5.0.1 on 2024-01-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_proxy', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedurl',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
