# Generated by Django 5.0.1 on 2024-01-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_proxy', '0006_alter_visitedurl_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedurl',
            name='data_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitedurl',
            name='data_sent',
            field=models.IntegerField(default=0),
        ),
    ]
