# Generated by Django 5.0.1 on 2024-01-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_proxy', '0008_createdsites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedurl',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
